name: flutter_interview_form
description: Multi-step form interview project
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.0

  # Local Storage
  shared_preferences: ^2.2.0

  # Utilities
  intl: ^0.18.1

  # UI
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
